import React from 'react';


export class HomePage extends React.Component {
    render() {
        return (
            <div className="container page-content">
                <h1>Vacay</h1>
                <p>Bacon ipsum dolor amet rump corned beef chuck biltong strip steak fatback, kielbasa shankle.  Pancetta cupim tri-tip sausage tail t-bone leberkas ground round sirloin doner pork.  Tenderloin fatback ribeye kevin pig, biltong strip steak rump shankle short loin.  T-bone kevin tongue, flank swine pork belly venison turducken picanha short ribs.  Pig cow kevin short ribs chicken tail ground round strip steak shoulder jerky doner tenderloin pork belly tongue.  Biltong buffalo boudin chicken hamburger, filet mignon pork alcatra prosciutto pork chop strip steak cow.  Meatball bresaola short loin andouille.</p>
                <p>Prosciutto shankle swine t-bone shoulder pig tail.  Pig strip steak alcatra, beef rump landjaeger pancetta capicola chicken frankfurter.  Hamburger ham hock ham bacon turkey flank.  Ribeye flank shoulder, tongue prosciutto jerky tri-tip turducken ham hock tenderloin.  Cupim corned beef turducken burgdoggen spare ribs filet mignon.  Prosciutto sausage porchetta, corned beef kielbasa fatback tongue meatball pork chop chuck ham jowl beef shoulder.  Jerky doner frankfurter jowl turkey.</p>
                <p>Bacon pork turducken, t-bone salami sirloin ball tip spare ribs ham hock frankfurter.  Hamburger pork loin cow bacon, fatback cupim frankfurter boudin ham hock.  Leberkas prosciutto jowl bacon boudin kevin ball tip pastrami brisket tenderloin jerky short ribs pork kielbasa.  Short loin pastrami jowl, brisket alcatra jerky sausage.  Drumstick picanha pig meatloaf ball tip, buffalo beef capicola andouille boudin landjaeger shank.</p>
                <p>Biltong corned beef sausage ball tip beef ribs burgdoggen.  Frankfurter kielbasa brisket tongue, tenderloin tail ball tip beef ribs t-bone hamburger filet mignon short ribs.  Pork chop shank buffalo short ribs capicola bacon, venison landjaeger leberkas tongue meatball andouille.  Cupim biltong shoulder frankfurter sirloin short loin prosciutto andouille tri-tip kevin, t-bone cow.  Burgdoggen ribeye beef ribs, bresaola andouille salami rump tenderloin cow.  Tri-tip hamburger ground round venison, pork loin meatball swine pork belly pork short loin sausage bresaola shank.</p>
                <p>Rump chuck pork prosciutto t-bone tongue.  Chuck shank ham hock beef ribs, cow turducken picanha kevin salami pig venison.  Pancetta tenderloin pork, capicola pork belly short loin landjaeger t-bone.  Beef sausage sirloin tri-tip, ribeye pig buffalo porchetta burgdoggen brisket jowl shankle salami chuck pork.</p>
                <p>Pastrami bacon pancetta fatback shoulder pork corned beef.  Pork chop biltong capicola, pork flank swine frankfurter filet mignon beef ribs prosciutto landjaeger sausage sirloin.  Beef doner tenderloin, pig burgdoggen meatball salami turducken tongue prosciutto meatloaf kevin tri-tip.  Pork loin ham sausage tri-tip shankle drumstick tenderloin t-bone bacon turducken frankfurter prosciutto tail biltong.  Hamburger biltong tri-tip, bresaola pastrami shankle beef ribs filet mignon shoulder tongue spare ribs.  Alcatra pork chop picanha pastrami turducken corned beef bacon landjaeger rump biltong.  Andouille tail pork capicola prosciutto fatback kielbasa pork chop.</p>
                <p>Jerky jowl pig swine ham hock turducken prosciutto.  T-bone turducken pancetta turkey.  Pancetta pig spare ribs ham hock fatback prosciutto tri-tip.  Ball tip tri-tip leberkas, frankfurter fatback short ribs tenderloin brisket salami burgdoggen pastrami.  Bacon beef tongue, andouille pig ribeye buffalo pork loin.  Alcatra chicken cow turkey.</p>
                <p>Jerky kevin hamburger, tenderloin leberkas porchetta pork rump pancetta swine pastrami beef turkey picanha tri-tip.  Pig pork loin pork belly, jerky hamburger venison sausage tenderloin shank pastrami swine sirloin.  Strip steak pork loin leberkas turducken, rump corned beef bacon tail doner.  Prosciutto ribeye turkey fatback t-bone, shank swine capicola short ribs pork belly bacon pancetta.</p>
                <p>Ribeye bresaola pastrami tenderloin jerky beef ribs burgdoggen alcatra pork loin t-bone filet mignon flank.  Swine ham fatback tenderloin spare ribs t-bone flank pork belly jerky pancetta.  Shoulder porchetta prosciutto frankfurter.  Rump ribeye cupim cow.  Leberkas burgdoggen doner rump andouille sausage chicken.  Jowl pork belly tri-tip, jerky alcatra salami kevin strip steak ham corned beef shoulder boudin tail ham hock.</p>
                <p>Filet mignon biltong tenderloin porchetta pig short loin, buffalo drumstick burgdoggen short ribs alcatra.  Beef ball tip porchetta, tenderloin boudin strip steak ham hock tongue turkey salami shank buffalo capicola ribeye.  Capicola t-bone tongue landjaeger pancetta.  Andouille alcatra capicola chicken leberkas bacon ham hock porchetta burgdoggen pork loin jowl beef pancetta pastrami.  Cow buffalo frankfurter, rump bacon prosciutto pork chop picanha kevin.  Swine meatball filet mignon kielbasa.</p>
                <p>Porchetta bacon tongue pork brisket pig landjaeger alcatra prosciutto.  Fatback alcatra prosciutto leberkas.  Kevin doner andouille drumstick jerky beef corned beef.  Jerky meatball shoulder, picanha landjaeger beef ribs andouille chuck frankfurter shankle ham pork loin venison meatloaf capicola.  Cow sausage ball tip, cupim ribeye turducken swine corned beef.</p>
                <p>Bresaola doner corned beef, ham shoulder andouille ham hock porchetta pork belly ribeye swine chuck.  Tenderloin picanha capicola, buffalo t-bone pork belly bresaola.  Tenderloin sausage shankle strip steak pork loin meatloaf pig tri-tip beef burgdoggen.  Meatloaf bresaola prosciutto kevin short loin doner frankfurter buffalo picanha chicken flank ribeye salami landjaeger brisket.  Ham spare ribs corned beef sausage landjaeger ham hock alcatra fatback rump short ribs.  Pig pork belly andouille flank turkey filet mignon.</p>
                <p>Burgdoggen ground round tri-tip turkey cow shank pancetta fatback salami doner beef ribs prosciutto.  Meatball kielbasa pancetta, bresaola porchetta kevin shankle shank chicken short loin turkey boudin leberkas.  Pastrami biltong spare ribs, corned beef pork loin swine chicken.  Drumstick pastrami andouille, prosciutto meatball alcatra frankfurter.  Chicken porchetta ribeye, kielbasa flank meatloaf short loin boudin brisket rump chuck.  Jowl short ribs kielbasa picanha.</p>
                <p>Spare ribs boudin corned beef buffalo, biltong brisket bresaola meatball jerky.  Sausage pork loin bresaola, venison ham beef bacon ribeye shoulder.  Buffalo pastrami bacon spare ribs, picanha short loin bresaola boudin.  Meatball flank tongue tenderloin pork loin, shoulder leberkas alcatra t-bone bacon pork belly.</p>
                <p>Biltong chicken pancetta bresaola porchetta ribeye kielbasa jowl boudin andouille, jerky burgdoggen buffalo.  Cupim shoulder fatback beef short ribs, brisket frankfurter sausage spare ribs bacon ham hock pig.  Picanha sirloin frankfurter, tongue brisket flank ground round hamburger doner cupim pastrami shoulder strip steak.  Flank picanha short ribs pork.  Short ribs chuck meatball cow prosciutto turducken ham hock cupim biltong, pork loin pork jerky.  Cow shoulder pork, turkey t-bone ham kevin shank rump tenderloin salami spare ribs.</p>
                <p>Shankle rump burgdoggen alcatra biltong tenderloin.  Short loin prosciutto leberkas chicken jowl ham, shankle shoulder corned beef tongue tri-tip brisket rump.  Hamburger frankfurter ground round ribeye ham hock.  Shoulder beef ribs sirloin corned beef, jerky brisket porchetta meatball salami andouille bacon jowl swine.  Swine turkey meatloaf beef sirloin ham hock landjaeger prosciutto pork chop tongue.  Bacon tri-tip pancetta filet mignon tongue shankle corned beef kevin capicola jowl flank ball tip sausage.  Salami jowl tail meatloaf beef ribs burgdoggen porchetta venison short loin.</p>
                <p>Cupim kevin burgdoggen beef jerky filet mignon swine pancetta short ribs bresaola.  Prosciutto spare ribs turkey, meatloaf shank strip steak beef tenderloin doner pig.  Short loin cupim short ribs cow t-bone chicken pancetta doner ball tip andouille landjaeger pork loin.  Burgdoggen shankle cow, ribeye brisket flank porchetta jowl capicola biltong salami short loin.</p>

            </div>
        );
    }
};

export default HomePage;